# This is a basic Salesforce CI workflow job

name: AutoValidate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or merge events but only for the "master" branch
  push:
    branches:
      - master
      - preprod
      - uat
      - sit

# Run the job
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
            image: salesforce/cli:latest-rc-full

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          clean: true
          set-safe-directory: true

      - name: install git delta
        run: |
          git config --global --add safe.directory /__w/githubactionsdemo/githubactionsdemo
          echo "y" | sf plugins install sfdx-git-delta
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir "."

      # place to see the job configuration
      - name: Print Job Configuration
        run: |
          sf version
          echo Branch Name: ${GITHUB_REF##*/}

      # Authentication URL of Target Org
      - name: Write the sfdxauthurl into a file
        # Secret name should only have captial letters and also should be same as the git workflow Target Org name (Correct: MYORG, Wrong: MyOrg).
        run: echo ${{ secrets.MYORG }} > sfdxauthurl.txt
      
      # Authenticate to Target Org
      - name: Authenticate to Target Org
        run: sf org login sfdx-url --sfdx-url-file sfdxauthurl.txt --set-default

      # run the build
      - name: Deploy source code
        run: 'sf project deploy start -x package/package.xml --post-destructive-changes destructiveChanges/destructiveChanges.xml -l RunLocalTests'